server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///leyou?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
mybatis-plus:
  type-aliases-package: com.leyou.order.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml
logging:
  level:
    com.leyou: debug

ly:
  #jwt相关配置
  jwt:
    pubKeyPath: E:\实习&培训&工作\黑马程序员培训\就业班内容\项目二阶段\个人代码\rsa-key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称
    application:
      serviceName: item-service
      secret: item-service
  #配置雪花算法里每台机器的编号(保证分布式ID不重复)
  worker:
    workerId: 1
    dataCenterId: 1